name: giphy-api
version: 0.6.0.0
synopsis: Giphy HTTP API wrapper and CLI search tool.
description: Please see README.md
homepage: http://github.com/passy/giphy-api#readme
license: BSD3
author: Pascal Hartig
maintainer: Pascal Hartig <phartig@rdrei.net>
category: Web
extra-source-files:
  - changelog.md
  - README.md
  - stack.yaml
  - test/fixtures/*.json

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmonomorphism-restriction

dependencies:
  - base >= 4.7 && < 5
  - text
  - network-uri

library:
  source-dirs: src
  dependencies:
    - aeson
    - containers
    - microlens
    - microlens-th
    - mtl
    - servant >= 0.13
    - servant-client >= 0.9
    - transformers
    - http-api-data
    - http-client
    - http-client-tls
  exposed-modules:
    - Web.Giphy

flags:
  buildSample:
    description: Build the sample application.
    default: false
    manual: true

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - giphy-api
      - aeson
      - basic-prelude
      - bytestring
      - containers
      - directory
      - hspec
      - lens

executables:
  giphy-search:
    main: Main.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    when:
      condition: flag(buildSample)
      then:
        dependencies:
          - giphy-api
          - lens
          - optparse-applicative
      else:
        buildable: false
