name: giphy-api
version: 0.1.0.0
synopsis: Giphy HTTP API wrapper and CLI search tool.
description: Please see README.md
homepage: http://github.com/passy/giphy-api#readme
license: BSD3
author: Pascal Hartig
maintainer: Pascal Hartig <phartig@rdrei.net>
category: Web

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fwarn-incomplete-record-updates
  - -fwarn-monomorphism-restriction
  - -fwarn-unused-do-bind

dependencies:
  - base >= 4.7 && < 5
  - text
  - network-uri

library:
  source-dirs: src
  dependencies:
    - aeson
    - containers
    - either
    - microlens
    - microlens-th
    - mtl
    - servant
    - servant-client
  other-modules:
    - Paths_giphy_api
  exposed-modules:
    - Web.Giphy

executables:
  giphy-search:
    main: Main.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - giphy-api
      - lens
      - optparse-applicative

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - giphy-api
      - aeson
      - basic-prelude
      - bytestring
      - containers
      - directory
      - hspec
      - lens
